### PR TITLE
refactored and updated scripts

### PR DESCRIPTION
**Pull request by derdritte**
From the commit-message:
- made all files pep8-conforming
- update readme
- added and exposed more options for gif-creating
- added more in-code documentation
- refactored config so arbitray movies can be added easily
- added functionality to search in all configured movies
- added and updated subtitle files
- added imageio dependency and removed images2gif.py

### CODE REVIEW

**Comment by derdritte** [comment]
This is my very first pull-request, if anyone can, I would appreciate any feedback or pointers.
As stated in #31 I have submitted this "omnibus"-pull-request in whole, but I am happy to fix up specific parts (formatting, documentation, features) before or after the pull-request is accepted.

**Comment by rmmh** [comment]
Don't put all this in one commit, it makes it essentially unreviewable. Every bullet point in your commit message should be a commit. You should have a commit for PEP8 conformance, which would be easy to validate as whitespace only changes, etc.

**Comment by LindseyB** [comment]
Hey, @derdritte thanks for the PR. It's quite large which I was expecting so I'm going to take a look. As @rmmh noted above it is useful to have separate commits so I can look at each of the code changes separate from one another as it is I'm probably just going to go through the code and then do some runs of it locally to see how it works.

**Comment by derdritte** [comment]
Hi @LindseyB and @rmmh! Thanks for the comments. I thought the PR would only be able to consist of one commit, so I basically worked against myself on this. In my local repo I have separated the changes I made into 4 commits (last one added basically while fixing my work up for the PR). They were still pretty messy as I wanted to implement a lot of changes.
I will definitely keep your pointers in mind for future PRs and hope my changes work properly on MacOS too, I sadly do not have a lot of testing-equipment (and I really did not want to test on Windows).

**Comment by LindseyB** [comment]
Okay I went through this on Linux and it works fine there. The code looks fine I don't much care if this works on windows honestly. It really hasn't in the past so no worries there.

**Comment by LindseyB** [comment]
Thanks for the PR 🎉

**Comment by derdritte** [comment]
Awesome, thank you for the quick review :)
I'll try and work on more stuff and make better PRs.

Issue #2 should be taken care off too.

**Pull request merged**
